name: 'UaiSO21 Package Action'
description: 'Builds UaiSO21 Packages'

inputs:
  package:
    description: 'PKGBUILD repo name'
    required: true
  source:
    description: 'custom package repo source'
    required: false
  branch:
    description: 'branch to build against'
    default: stable
    required: false
  custom-repo:
    description: 'custom repo'
    required: false
  multilib:
    description: 'build multilib package'
    required: false
    default: false
  repo:
    description: 'package repo'
    required: true
  gpg-key:
    descriptio: 'gpg signing key'
    required: true
  gpg-passphrase:
    description: 'gpg passphrase'
    required: true
  ssh-key:
    description: 'boxit user ssh private key'
    required: false
  extrarepo:
    description: 'extra repository to buld package'
    required: false
  gitbranch:
    description: 'extra repository to buld package'
    required: false

runs:
  using: "composite"
  steps:
    - name: install build-dependencies
      shell: bash
      run: |
        echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
        pacman -Syu --noconfirm --needed \
        pacman \
        sudo \
        git \
        github-cli \
        openssh \
        gnupg \
        coreutils \
        rsync \
        wget \
        fakeroot \
        binutils \
        cmake \
        gcc \
        make \
        devtools \
        acl \
        archlinux-keyring \
        autoconf \
        automake \
        binutils \
        bison \
        btrfs-progs \
        cryptsetup \
        db \
        debugedit \
        diffutils \
        dnssec-anchors \
        fakeroot \
        flex \
        gc \
        gcc-libs \
        git \
        glib2 \
        groff \
        grub \
        guile \
        iputils \
        jansson \
        ldns \
        libedit \
        libisl \
        libmpc \
        libnghttp2 \
        libnl \
        libp11-kit \
        libpcap \
        libpsl \
        libsasl \
        libseccomp \
        libsecret \
        libssh2 \
        libsysprof-capture \
        libtasn1 \
        libtirpc \
        libtool \
        libunistring \
        libverto \
        libxcrypt \
        libxml2 \
        licenses \
        linux \
        linux-api-headers \
        linux-firmware \
        linux-firmware-whence \
        lz4 \
        lzo \
        m4 \
        make \
        mkinitcpio \
        mkinitcpio-busybox \
        mpfr \
        nano \
        ncurses \
        nettle \
        npth \
        openssh \
        openssl \
        p11-kit \
        pacman-mirrorlist \
        pam \
        pambase \
        patch \
        pciutils \
        pcre2 \
        perl \
        perl-error \
        perl-mailtools \
        perl-timedate \
        pinentry \
        pkgconf \
        popt \
        procps-ng \
        psmisc \
        readline \
        sed \
        shadow \
        sqlite \
        sudo \
        systemd \
        systemd-libs \
        systemd-sysvcompat \
        tar \
        texinfo \
        tpm2-tss \
        tzdata \
        util-linux \
        util-linux-libs \
        which \
        xz \
        zlib \
        zram-generator \
        zstd
        #extra-cmakemodules \
    
#     - name: Add UaiSO21 Repo and Key
#       shell: bash
#       run: |
#         #add UaiSO21 archlinux repository
#         echo '
#         [uaiso-dev]
#         SigLevel = PackageRequired
#         Server = https://repo..com.br/archlinux/$arch' | tee -a /etc/pacman.conf
#         
#         echo '
#         [uaiso-testing]
#         SigLevel = PackageRequired
#         Server = https://repo..com.br/stable/$arch' | tee -a /etc/pacman.conf
#         
#         echo '
#         [uaiso-stable]
#         SigLevel = PackageRequired
#         Server = https://repo..com.br/stable/$arch' | tee -a /etc/pacman.conf
#         
#         sed -i '/PACKAGER=/s/#PACKAGER=.*/\PACKAGER="BigLinux Package Build <bigbruno@gmail.com>\"/' /etc/makepkg.conf
#         
#         
#         #add UaiSO21 Keyring
#         git clone --depth 1 https://github.com/UaiSO21/xxx-keyring.git
#         pushd xxx-keyring
#           install -m0644 xxx.gpg /usr/share/pacman/keyrings/
#           install -m0644 xxx-trusted /usr/share/pacman/keyrings/
#           install -m0644 xxx-trusted /usr/share/pacman/keyrings/
#         popd
#         rm -rf xxx-keyring
#         
#         pacman-key --init
#         pacman-key --populate archlinux UaiSO21
#         
#         pacman -Sy
      
    - name: Makepkg Build    
      shell: bash
      run: |
        useradd builduser -m 
        passwd -d builduser 
        printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
        
        git clone ${{ github.event.client_payload.url }}.git
        gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
        chmod 777 $gitfolder
        cd $gitfolder
        
        sudo -u builduser bash -c 'makepkg -sc --noconfirm --skippgpcheck'
        
        ls -lh
        
    - name: Rename Package
      shell: bash -O extglob {0}
      run: | 
        # "Rename Package"
        gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
        cd $gitfolder
        for i in *.zst; do if [ -n "$(ls $i | grep :)" ]; then mv $i $(echo $i | sed 's/:/-/'); fi; done
      
        
    - name: sign package
      shell: bash -O extglob {0}
      run: |
        # "Assinar Pacote"
        cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import &>/dev/null
        gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
        cd $gitfolder
        for p in $(find $PWD -maxdepth 1 -regex '.*\.pkg\.tar\.\(xz\|zst\)'); do
          gpg --pinentry-mode loopback --passphrase "${{ secrets.PASSPHRASE }}" --detach-sign ${p}
        done
    
    - name: CheckSum
      shell: bash -O extglob {0}
      run: |
        # "Checksum"
        gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
        cd $gitfolder
        echo '#!/bin/bash
        for i in $(ls *.zst); do md5sum $i >> $i.md5; done
        for i in $(ls *.sig | sed 's/.sig//'); do md5sum $i.sig >> $i.md5; done
        exit 0' > md5.sh
        bash md5.sh
