name: Package Build Teste

on:
  repository_dispatch:
    types:
      - UaiSO/*
      - '**'
      
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v3
       
      - name: Push to Repo
        shell: bash
        run: |
          # "Assinar Pacote"
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import &>/dev/null
          
      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
