### NÃO EDITAR ###### NÃO EDITAR ###
name: Copy Arch, Chaotic, BigLinux Daily
### NÃO EDITAR ###

### NÃO EDITAR ###
on:
### NÃO EDITAR ###
  # repository_dispatch:
    # types:
    #   - '*'
    
  schedule:
    - cron:  '00 21 * * *'
    
  ### NÃO EDITAR ###
  workflow_dispatch:
  ### NÃO EDITAR ###

### NÃO EDITAR ###
jobs:
  ### NÃO EDITAR ###
  build:
    ### NÃO EDITAR ###
    runs-on: ubuntu-latest
    ### NÃO EDITAR ###
    container: archlinux:latest
    ### NÃO EDITAR ###
    steps:
      ### NÃO EDITAR ###
      - uses: actions/checkout@v3
      ### NÃO EDITAR ###
      - name: Install Dependencies
      ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        run: |
          ### NÃO EDITAR ###
          pacman-key --init
          ### NÃO EDITAR ###
          #add multilib
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          
          
          
          #add ChaoticAUR
          pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key FBA220DFC880C036
          
          pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm
          
          echo '
          [chaotic-aur]
          Server = https://us-fl-mirror.chaotic.cx/$repo/$arch' | tee -a /etc/pacman.conf

          #add Garuda
         
          echo '
          [garuda]
          Server = https://us-fl-mirror.chaotic.cx/$repo/$arch' | tee -a /etc/pacman.conf
          
          #add AndontieAUR
          pacman-key --recv-key B545E9B7CD906FE3
          pacman-key --lsign-key B545E9B7CD906FE3

          echo '
          [andontie-aur]
          SigLevel = PackageRequired
          Server = https://aur.andontie.net/$arch' | tee -a /etc/pacman.conf

          #add BigLinux
          pacman-key -r 45EC44879815E2A6
          pacman-key --lsign-key 45EC44879815E2A6
          
          echo '
          [biglinux-archlinux]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/archlinux/$arch' | tee -a /etc/pacman.conf
          
          echo '
          [biglinux-stable]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/stable/$arch' | tee -a /etc/pacman.conf
          
          #add ALCI
          
          echo '
          [alci_repo]
          SigLevel = Optional TrustAll
          Server = https://arch-linux-calamares-installer.github.io/$repo/$arch' | tee -a /etc/pacman.conf

          #add ArcoLinux
          pacman-key -r 74F5DE85A506BF64
          pacman-key --lsign-key 74F5DE85A506BF64

          echo '
          [arcolinux_repo]
          SigLevel = Required DatabaseOptional
          Server = https://gitlab.com/arcolinux/$repo/-/raw/main/$arch' | tee -a /etc/pacman.conf

          echo '
          [arcolinux_repo_3party]
          SigLevel = Required DatabaseOptional
          Server = https://gitlab.com/arcolinux/$repo/-/raw/main/$arch' | tee -a /etc/pacman.conf

          echo '
          [arcolinux_repo_xlarge]
          SigLevel = Required DatabaseOptional
          Server = https://gitlab.com/arcolinux/$repo/-/raw/main/$arch' | tee -a /etc/pacman.conf

          #add Xerolinux
          echo '
          [xerolinux_repo]
          SigLevel = Optional TrustAll
          Server = https://mirror.accum.se/mirror/xerolinux.xyz/$repo/$arch' | tee -a /etc/pacman.conf
          
          echo '
          [xerolinux_repo_xl]
          SigLevel = Optional TrustAll
          Server = https://mirror.accum.se/mirror/xerolinux.xyz/$repo/$arch' | tee -a /etc/pacman.conf

          echo '
          [xerolinux_nvidia_repo]
          SigLevel = Optional TrustAll
          Server = https://mirror.accum.se/mirror/xerolinux.xyz/$repo/$arch' | tee -a /etc/pacman.conf
          
          
          
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          sed -i '/ParallelDownloads/s/=.*/= 8/' /etc/pacman.conf
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          sed -i '/NoProgressBar/s/^/#/' /etc/pacman.conf
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          sed -i '/VerbosePkgLists/s/^/#/' /etc/pacman.conf
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          #reflector --sort rate -l 10 --save /etc/pacman.d/mirrorlist
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          echo '#Server = https://mirror.osbeck.com/archlinux/$repo/os/$arch
          #Server = https://arch.mirror.constant.com/$repo/os/$arch
          Server = https://mirror.pseudoform.org/$repo/os/$arch
          Server = https://mirror.theo546.fr/archlinux/$repo/os/$arch
          Server = rsync://mirror.theo546.fr/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ####
          pacman -Syu --noconfirm --needed sudo git github-cli openssh gnupg coreutils rsync wget
          ### NÃO EDITAR ###### NÃO EDITAR ####
          pacman -Scc --noconfirm
          ### NÃO EDITAR ###### NÃO EDITAR ####
          
      # # Tmate ##
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      
      ### NÃO EDITAR ####
      - name: Download
        ### NÃO EDITAR ####
        shell: bash
        ### NÃO EDITAR ####
        run: |
          ### NÃO EDITAR ####
          mkdir x86_64
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          cat list-packages-daily list-packages-hour list-packages-manual > packages.txt
          ### NÃO EDITAR ####### NÃO EDITAR ####
          sed -i '/#/d' packages.txt
          ### NÃO EDITAR ####### NÃO EDITAR ####
          sed -i ':a;$!N;s/\n/ /;ta;' packages.txt
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ####
          grep -v -f list-packages-local packages.txt > packages-download.txt
          ### NÃO EDITAR ###
          mkdir -p /tmp/pacmandb
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ####
          pacman -Syw --noconfirm $(cat packages-download.txt) --cachedir $PWD/x86_64 --dbpath /tmp/pacmandb
          ### NÃO EDITAR ###
          rm packages.txt
          ### NÃO EDITAR ###
          rm packages-download.txt
          
      ### NÃO EDITAR ####### NÃO EDITAR ####
      - name: Remove Existing Packages
        ### NÃO EDITAR ####
        shell: bash
        ### NÃO EDITAR ####
        run: |
          ### NÃO EDITAR ####
          cd x86_64
          ### NÃO EDITAR ####
          rm *.sig
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          ls *.pkg* | rev | cut -d "/" -f1 | rev > packages-local-download
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          wget http://repo-uaiso.uai21.com/dev/x86_64/packages
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          grep -f packages-local-download packages >> ../preListaExclude
          ### NÃO EDITAR ####### NÃO EDITAR ####### NÃO EDITAR ####
          for i in $(cat packages); do 
            ### NÃO EDITAR ####
            if [ -e "$i" ]; then
              ### NÃO EDITAR ####
              rm $i
            ### NÃO EDITAR ####
            fi
          ### NÃO EDITAR ####
          done
          ### NÃO EDITAR ####
          rm packages
          ### NÃO EDITAR ####
          rm packages-local-download
          ### NÃO EDITAR ####
          ls -lha
      
      ### NÃO EDITAR ###
      - name: Sign Package
        ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        run: |
          echo ### Sign Package ###
          ### NÃO EDITAR ###
          cd x86_64
          ### NÃO EDITAR ###
          # "Assinar Pacote"
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import &>/dev/null
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          for p in $(find $PWD -maxdepth 1 -regex '.*\.pkg\.tar\.\(xz\|zst\)'); do
            ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
            gpg --pinentry-mode loopback --passphrase "${{ secrets.PASSPHRASE }}" --detach-sign ${p}
          ### NÃO EDITAR ###
          done
          ### NÃO EDITAR ###
          ls -lh
        
      ### NÃO EDITAR ###
      - name: Push to Repo
        ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        run: |
          echo "## Push to Repo ##"
          ### NÃO EDITAR ###
          mkdir -p /home/runner/.ssh
          ### NÃO EDITAR ###### NÃO EDITAR ###
          touch /home/runner/.ssh/id_rsa
          ### NÃO EDITAR ###### NÃO EDITAR ###
          chmod 600 /home/runner/.ssh/id_rsa
          ### NÃO EDITAR ###### NÃO EDITAR ###
          ssh-agent -a /tmp/ssh_agent.sock > /dev/null
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          echo "${{ secrets.REPO_SSH_KEY }}" >> /home/runner/.ssh/id_rsa
          ### NÃO EDITAR ###
          eval `ssh-agent -s`
          ### NÃO EDITAR ###### NÃO EDITAR ###
          ssh-add /home/runner/.ssh/id_rsa
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          ssh-keyscan -t rsa -p ${{ secrets.REPO_PORT }} ${{ secrets.REPO_HOST }} >> /home/runner/.ssh/known_hosts
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          # cd x86_64
          ### NÃO EDITAR ###
          # ls -lh x86_64
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          # #select branch
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          # if [ -n "$(echo ${{ github.event.client_payload.branch }} | grep stable )" ];then
          ### NÃO EDITAR ###
          #   branch=stable
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          # elif [ -n "$(echo ${{ github.event.client_payload.branch }} | grep testing )" ];then
          ### NÃO EDITAR ###
          #   branch=testing
          ### NÃO EDITAR ###
          # else
          ### NÃO EDITAR ###
          #   branch=dev
          ### NÃO EDITAR ###
          # fi
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          #lista local
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          for i in $(cat preListaExclude); do echo "--exclude=${i} " >> listaExclude ; done
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          for i in $(cat preListaExclude); do echo "--exclude=${i}.sig " >> listaExclude ; done
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          for i in $(cat list-packages-local); do echo "--exclude=$i*.* " >> listaExclude ; done
          
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          
          
          
          
          
          echo ${{ secrets.SYNK_TOKEN }} | gh auth login --with-token
          
          #for i in $(h repo list  UaiSO21 -L 100 | awk '{print $1}' | awk -F/ '{print $2}' | grep uaiso-); do echo "--exclude=$i*.* " >> listaExclude ; done
          
          unlist=(uaiso-kernel-linux github)

          for i in $(gh repo list --visibility public UaiSO21 | awk '{print $1}' | awk -F/ '{print $2}'); do
            echo $unlist | grep $i
            if [ -z "$(echo $unlist | grep $i)" ]; then
              name=
              gh repo clone UaiSO21/$i
              pushd $i
                gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
                if [ -n "$gitfolder" ]; then
                  cd $gitfolder
                  name=$(cat PKGBUILD | grep pkgname= | cut -d "=" -f2)
                  popd
                  if [ -n "$name" ]; then
                    echo "--exclude=${name}*.* " >> listaExclude
                  fi
                else
                  popd
                fi
            fi
          done
          
          
          
          
          
          
          ### NÃO EDITAR ###### NÃO EDITAR ###
          sed -i '/#/d' list-packages-aur
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          for i in $(cat list-packages-aur); do echo "--exclude=$(echo $i | cut -d ":" -f1)*.* " >> listaExclude ; done
          ### NÃO EDITAR ###### NÃO EDITAR ###
          listaExclude=$(cat listaExclude)
          ### NÃO EDITAR ###
          cat listaExclude
          ### NÃO EDITAR ###
          # mv x86_64 $branch
          ### NÃO EDITAR ###
          du -h x86_64
          ### NÃO EDITAR ###
          touch x86_64/zzz.txt
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          rsync --dry-run --stats -vapzOh --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.REPO_PORT }}" x86_64 ${{ secrets.REPO_USER }}@${{ secrets.REPO_HOST }}:${{ secrets.REPO_DIR_PACKAGE }} --exclude=*.html --exclude=*.db* --exclude=*.files* $(cat listaExclude)
          #--dry-run 
          ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
          
      # # Tmate ##
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      
#       ### NÃO EDITAR ###
#       - name: Telegram Alert Success
#       ### NÃO EDITAR ###
#         shell: bash -O extglob {0}
#         ### NÃO EDITAR ###
#         run: |
#             ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
#             curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.TELEGRAM_TO }}", "text": "${{ github.workflow }} Gerado com Sucesso.", "disable_notification": false, "disable_web_page_preview": true, "is_topic_message": "true", "message_thread_id": "6"}' ${{ secrets.TELEGRAM_TOKEN }}
#             ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
#       
#       ### NÃO EDITAR ###
#       - name: Telegram Alert Fail
#         ### NÃO EDITAR ###
#         if: ${{ failure() }}
#         ### NÃO EDITAR ###
#         run: |
#           ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
#           curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.TELEGRAM_TO }}", "text": "FALHA ao gerar ${{ github.workflow }}, link do erro: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}", "disable_notification": false, "message_thread_id": "6"}' ${{ secrets.TELEGRAM_TOKEN }}
#           ### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###### NÃO EDITAR ###
