### NÃO EDITAR ###
name: Package Build AUR
### NÃO EDITAR ###

### NÃO EDITAR ###
on:
  ### NÃO EDITAR ###
  schedule:
  ### NÃO EDITAR ###
  
  
    - cron:  '0 19 * * *'
    
  workflow_dispatch:

### NÃO EDITAR ###
jobs:
  ### NÃO EDITAR ###
  build:
    ### NÃO EDITAR ###
    runs-on: ubuntu-latest
    ### NÃO EDITAR ###
    steps:
      ### NÃO EDITAR ###
      - uses: actions/checkout@v3
      ### NÃO EDITAR ###
      - name: install build-dependencies
        ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        run: |
          ### NÃO EDITAR ###
          sudo apt-get update
          ### NÃO EDITAR ###
          sudo apt-get install \
          build-essential \
          cmake \
          fakeroot \
          git \
          libarchive-dev \
          libarchive-tools \
          libcurl4-openssl-dev \
          libgpgme-dev \
          libssl-dev \
          zip \
          python3-pip
          ### NÃO EDITAR ###
          sudo pip3 install meson
          ### NÃO EDITAR ###
          sudo pip3 install ninja
          ### NÃO EDITAR ###
          
      ### NÃO EDITAR ###
      - name: install pacman
        ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        env:
          ### NÃO EDITAR ###
          PACMAN_VERSION: 6.0.1
        ### NÃO EDITAR ###
        run: |
          ### NÃO EDITAR ###
          sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
          ### NÃO EDITAR ###
          sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
          ### NÃO EDITAR ###
          pushd pacman-${PACMAN_VERSION}
          ### NÃO EDITAR ###
          # sudo patch -p1 -i ../pacman-sync-first-option.patch
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          sudo meson --prefix=/usr \
                      --buildtype=plain \
                      -Ddoc=disabled \
                      -Ddoxygen=enabled \
                      -Dscriptlet-shell=/usr/bin/bash \
                      -Dldconfig=/usr/bin/ldconfig \
                      build
                      ### NÃO EDITAR ###
                      ### NÃO EDITAR ###
                      ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          sudo meson compile -C build
          ### NÃO EDITAR ###
          sudo meson install -C build
          ### NÃO EDITAR ###
          popd
          ### NÃO EDITAR ###
          # sudo install -m644 pacman.conf /etc/pacman.conf
          ### NÃO EDITAR ###
          # sudo install -m644 makepkg.conf /etc/
          ### NÃO EDITAR ###
          sudo mkdir -p /etc/pacman.d
          ### NÃO EDITAR ###
          sudo touch /etc/pacman.d/mirrorlist
          ### NÃO EDITAR ###
          # popd
          ### NÃO EDITAR ###
          sudo rm -rf pacman-${PACMAN_VERSION}*
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          #add UaiSo repository
          echo '
          [uaiso21-stable-update]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/stable-update/$arch' | sudo tee -a /etc/pacman.conf
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          echo '
          [uaiso21-dev]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/dev/$arch' | sudo tee -a /etc/pacman.conf
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          echo '
          [uaiso21-testing]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/testing/$arch' | sudo tee -a /etc/pacman.conf
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          echo '
          [uaiso21-stable]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/stable/$arch' | sudo tee -a /etc/pacman.conf
          ### NÃO EDITAR ###
          
      ### NÃO EDITAR ###
      - name: install keyrings
        ### NÃO EDITAR ###
        shell: bash
        ### NÃO EDITAR ###
        run: |
          ### NÃO EDITAR ###
          sudo install -dm755 /usr/share/pacman/keyrings/
          ### NÃO EDITAR ###
          mkdir -p archlinux-keyring
          ### NÃO EDITAR ###
          pushd archlinux-keyring
            ### NÃO EDITAR ###
            wget https://archlinux.org/packages/core/any/archlinux-keyring/download -O /tmp/archlinux-keyring.tar.zst
            ### NÃO EDITAR ###
            tar --use-compress-program=unzstd --strip-components=4 --wildcards -xvf /tmp/archlinux-keyring.tar.zst usr/share/pacman/keyrings/*
            ### NÃO EDITAR ###
            sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
            sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
            sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          popd
          ### NÃO EDITAR ###
          sudo rm -rf archlinux-keyring
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          sudo git clone --depth 1 https://github.com/UaiSO21/uaiso-keyring.git
          ### NÃO EDITAR ###
          pushd uaiso-keyring
            ### NÃO EDITAR ###
            sudo install -m0644 uaiso21.gpg /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
            sudo install -m0644 uaiso21-trusted /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
            sudo install -m0644 uaiso21-revoked /usr/share/pacman/keyrings/
            ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          popd
          ### NÃO EDITAR ###
          sudo rm -rf uaiso-keyring
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          sudo pacman-key --init
          ### NÃO EDITAR ###
          sudo pacman-key -r FB39C5D54771F074
          ### NÃO EDITAR ###
          sudo pacman-key --lsign-key FB39C5D54771F074
          ### NÃO EDITAR ###
          sudo pacman-key --populate archlinux uaiso21
          ### NÃO EDITAR ###
          
      # ## Tmate ##
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3 
      
      ### NÃO EDITAR ###
      - name: Send Hooks
        ### NÃO EDITAR ###
        shell: bash -O extglob {0}
        ### NÃO EDITAR ###
        env:
          ### NÃO EDITAR ###
          CHAVE: ${{ secrets.WEBHOOK_TOKEN }}
        ### NÃO EDITAR ###
        run: |
          ### NÃO EDITAR ###
          sudo pacman -Sy
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          webhooks() {
          ### NÃO EDITAR ###
          echo '
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: token '$CHAVE'" \
          --data '"'{"'"event_type"'": "'"'AUR/$pkgname'"'", "'"client_payload"'": { "'"url"'": "'"'$pkgurl'"'"}}'"' \
          'https://api.github.com/repos/UaiSO21/uaiso-packages-build/dispatches'' > run-webhooks-aur.sh
          bash -x run-webhooks-aur.sh
          rm run-webhooks-aur.sh
          ### NÃO EDITAR ###
          }
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          ### NÃO EDITAR ###
          
          ### NÃO EDITAR ###
          for i in $(cat list-packages-aur); do pkg=$i
              ### NÃO EDITAR ###
              pkgname=$(echo $pkg | cut -d ":" -f1)
              ### NÃO EDITAR ###
              pkgurl=$(echo $pkg | cut -d ":" -f2,3)
              ### NÃO EDITAR ###
              if [ -z "$(echo $i)" -o -z "$(echo $i | grep \#)" ];then
                  ### NÃO EDITAR ###
                  #limpa todos os $
                  ### NÃO EDITAR ###
                  veraur=
                  ### NÃO EDITAR ###
                  pkgver=
                  ### NÃO EDITAR ###
                  pkgrel=
                  ### NÃO EDITAR ###
                  #versão do AUR
                  ### NÃO EDITAR ###
                  git clone ${pkgurl}
                  ### NÃO EDITAR ###
                  cd $(echo ${pkgurl} | rev | cut -d "/" -f1 | rev | cut -d "." -f1)
                  ### NÃO EDITAR ###
                  source PKGBUILD
                  ### NÃO EDITAR ###
                  veraur=$pkgver-$pkgrel
                  ### NÃO EDITAR ###
                  cd ..
                  ### NÃO EDITAR ###
                  if [ "$pkgname" != "$(echo $pkg | cut -d ":" -f1)" ]; then
                      ### NÃO EDITAR ###
                      pkgname=$(echo $pkg | cut -d ":" -f1)
                  ### NÃO EDITAR ###
                  fi
                  
                  ### NÃO EDITAR ###
                  repo=uaiso21-dev
                  
                  ### NÃO EDITAR ###
                  verrepo=
                  ### NÃO EDITAR ###
                  verrepo=$(pacman -Ss $pkgname | grep $repo | grep -v "$pkgname-" | grep -v "\-$pkgname" | grep -w "$pkgname" | cut -d " " -f2 | cut -d ":" -f2)
                  
                  ### NÃO EDITAR ###
                  #se versão do AUR foi maior que a versão do repo local
                  ### NÃO EDITAR ###
                  if [ "$veraur" != "$verrepo" ]; then
                      ### NÃO EDITAR ###
                      echo -e "Enviando \033[01;31m$pkgname\033[0m para Package Build"
                      ### NÃO EDITAR ###
                      echo " AUR ""$pkgname"="$veraur"
                      ### NÃO EDITAR ###
                      echo "Repo ""$pkgname"="$verrepo"
                      ### NÃO EDITAR ###
                      webhooks
                      ### NÃO EDITAR ###
                  ### NÃO EDITAR ###
                  else
                      ### NÃO EDITAR ###
                      echo "Versão do $pkgname é igual !"
                  ### NÃO EDITAR ###
                  fi
              ### NÃO EDITAR ###
              fi
          ### NÃO EDITAR ###
          done 
      ### NÃO EDITAR ###
  ### NÃO EDITAR ###
### NÃO EDITAR ###
