name: Package Build AUR

on:
  schedule:
    - cron:  '0 19 * * *'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: install build-dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
          build-essential \
          cmake \
          fakeroot \
          git \
          libarchive-dev \
          libarchive-tools \
          libcurl4-openssl-dev \
          libgpgme-dev \
          libssl-dev \
          zip \
          python3-pip
          sudo pip3 install meson
          sudo pip3 install ninja
          
      - name: install pacman
        shell: bash
        env:
          PACMAN_VERSION: 6.0.1
        run: |
          sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
          sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
          pushd pacman-${PACMAN_VERSION}
          # sudo patch -p1 -i ../pacman-sync-first-option.patch
          sudo meson --prefix=/usr \
                      --buildtype=plain \
                      -Ddoc=disabled \
                      -Ddoxygen=enabled \
                      -Dscriptlet-shell=/usr/bin/bash \
                      -Dldconfig=/usr/bin/ldconfig \
                      build
          sudo meson compile -C build
          sudo meson install -C build
          popd
          # sudo install -m644 pacman.conf /etc/pacman.conf
          # sudo install -m644 makepkg.conf /etc/
          sudo mkdir -p /etc/pacman.d
          sudo touch /etc/pacman.d/mirrorlist
          # popd
          sudo rm -rf pacman-${PACMAN_VERSION}*
          
          #add UaiSo repository
          echo '
          [uaiso21-stable-update]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/stable-update/$arch' | sudo tee -a /etc/pacman.conf
          
          echo '
          [uaiso21-dev]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/dev/$arch' | sudo tee -a /etc/pacman.conf
          
          echo '
          [uaiso21-testing]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/testing/$arch' | sudo tee -a /etc/pacman.conf
          
          echo '
          [uaiso21-stable]
          SigLevel = PackageRequired
          Server = http://repo-uaiso.uai21.com/stable/$arch' | sudo tee -a /etc/pacman.conf
          
      - name: install keyrings
        shell: bash
        run: |
          sudo install -dm755 /usr/share/pacman/keyrings/
          
          mkdir -p archlinux-keyring
          pushd archlinux-keyring
            wget https://archlinux.org/packages/core/any/archlinux-keyring/download -O /tmp/archlinux-keyring.tar.zst
            tar --use-compress-program=unzstd --strip-components=4 --wildcards -xvf /tmp/archlinux-keyring.tar.zst usr/share/pacman/keyrings/*
            sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
            sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf archlinux-keyring
          
          sudo git clone --depth 1 https://github.com/UaiSO21/uaiso-keyring.git
          pushd uaiso-keyring
            sudo install -m0644 uaiso21.gpg /usr/share/pacman/keyrings/
            sudo install -m0644 uaiso21-trusted /usr/share/pacman/keyrings/
            sudo install -m0644 uaiso21-revoked /usr/share/pacman/keyrings/
          popd
          sudo rm -rf uaiso-keyring
                  
          sudo pacman-key --init
          sudo pacman-key -r FB39C5D54771F074
          sudo pacman-key --lsign-key FB39C5D54771F074
          sudo pacman-key --populate archlinux uaiso21
          
      # ## Tmate ##
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3 
      
      - name: Send Hooks
        shell: bash -O extglob {0}
        env:
          CHAVE: ${{ secrets.WEBHOOK_TOKEN }}
        run: |
          sudo pacman -Sy
          
          webhooks() {
          echo '
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: token '$CHAVE'" \
          --data '"'{"'"event_type"'": "'"'AUR/$pkgname'"'", "'"client_payload"'": { "'"url"'": "'"'$pkgurl'"'"}}'"' \
          'https://api.github.com/repos/UaiSO21/uaiso-packages-build/dispatches'' > run-webhooks-aur.sh

          bash -x run-webhooks-aur.sh
          rm run-webhooks-aur.sh
          }
          
          for i in $(cat list-packages-aur); do pkg=$i
              pkgname=$(echo $pkg | cut -d ":" -f1)
              pkgurl=$(echo $pkg | cut -d ":" -f2,3)
              if [ -z "$(echo $i)" -o -z "$(echo $i | grep \#)" ];then
                  #limpa todos os $
                  veraur=
                  pkgver=
                  pkgrel=
                  #versão do AUR
                  git clone ${pkgurl}
                  cd $(echo ${pkgurl} | rev | cut -d "/" -f1 | rev | cut -d "." -f1)
                  source PKGBUILD
                  veraur=$pkgver-$pkgrel
                  cd ..
                  if [ "$pkgname" != "$(echo $pkg | cut -d ":" -f1)" ]; then
                      pkgname=$(echo $pkg | cut -d ":" -f1)
                  fi
                  
                  repo=uaiso21-dev
                  
                  verrepo=
                  verrepo=$(pacman -Ss $pkgname | grep $repo | grep -v "$pkgname-" | grep -v "\-$pkgname" | grep -w "$pkgname" | cut -d " " -f2 | cut -d ":" -f2)
                  
                  #se versão do AUR foi maior que a versão do repo local
                  if [ "$veraur" != "$verrepo" ]; then
                      echo -e "Enviando \033[01;31m$pkgname\033[0m para Package Build"
                      echo " AUR ""$pkgname"="$veraur"
                      echo "Repo ""$pkgname"="$verrepo"
                      webhooks
                  else
                      echo "Versão do $pkgname é igual !"
                  fi
              fi
          done 
          
